document.head.innerHTML += 
	'<meta charset="UTF-8">'
	+'<meta http-equiv="X-UA-Compatible" content="ie=edge">'
	+'<meta name="viewport" content="width=device-width, initial-scale=1.0">'
	+'<meta name="msapplication-config" content="/browserconfig.xml">'
	+'<meta name="msapplication-TileColor" content="#ff009d">'
	+'<meta name="application-name" content="frankpettersson.se">'
	+'<meta name="apple-mobile-web-app-title" content="frankpettersson.se">'
	+'<meta name="frankpettersson.se" content="#FFFFFF">'
	+'<meta name="Description" content="JavaScript/HTML canvas art and games">'
	+'<meta name="theme-color" content="#FFFFFF"/>'
	+'<link rel="apple-touch-icon" sizes="180x180" href="/assets/images/icons/apple-touch-icon.png">'
	+'<link rel="icon" type="image/png" sizes="32x32" href="/assets/images/icons/favicon-32x32.png">'
	+'<link rel="icon" type="image/png" sizes="16x16" href="/assets/images/icons/favicon-16x16.png">'
	+'<link rel="mask-icon" href="/assets/images/icons/safari-pinned-tab.svg" color="#ff009d">'
	+'<link rel="shortcut icon" href="/assets/images/icons/favicon.ico">'
	+'<link rel="manifest" href="/site.webmanifest">';