let link1 = document.createElement('link');
	link1.rel = 'apple-touch-icon';
	link1.sizes = '180x180';
	link1.href = '/assets/images/icons/apple-touch-icon.png';
let link2 = document.createElement('link');
	link2.rel = 'icon';
	link2.sizes = '32x32';
	link2.href = '/assets/images/icons/favicon-32x32.png';
let link3 = document.createElement('link');
	link3.rel = 'icon';
	link3.sizes = '16x16';
	link3.href = '/assets/images/icons/favicon-16x16.png';
let link4 = document.createElement('link');
	link4.rel = 'mask-icon';
	link4.href = '/assets/images/icons/safari-pinned-tab.svg';	
	link4.color = '#ff009d';
let link5 = document.createElement('link');
	link5.rel = 'shortcut icon';
	link5.href = '/assets/images/icons/favicon.ico';
let link6 = document.createElement('link');
	link6.rel = 'manifest';
	link6.href = '/site.webmanifest';
document.head.appendChild(link1);
document.head.appendChild(link2);
document.head.appendChild(link3);
document.head.appendChild(link4);
document.head.appendChild(link5);
document.head.appendChild(link6);

let meta1 = document.createElement('meta');
	meta1.charset = 'UTF-8';
let meta2 = document.createElement('meta');
	meta2.httpEquiv = 'X-UA-Compatible';
	meta2.content = 'ie=edge';
let meta3 = document.createElement('meta');
	meta3.name = 'viewport';
	meta3.content = 'width=device-width, initial-scale=1.0';
let meta4 = document.createElement('meta');
	meta4.name = 'masapplication-config';
	meta4.content = '/browserconfig.xml';
let meta5 = document.createElement('meta');
	meta5.name = 'msapplication-TileColor';
	meta5.content = '#ff009d';
let meta6 = document.createElement('meta');
	meta6.name = 'application-name';
	meta6.content = 'frankpettersson.se';
let meta7 = document.createElement('meta');
	meta7.name = 'apple-mobile-web-app-title';
	meta7.content = 'frankpettersson.se';
let meta8 = document.createElement('meta');
	meta8.name = 'frankpettersson.se';
	meta8.content = '#ffffff';
let meta9 = document.createElement('meta');
	meta9.name = 'Description';
	meta9.content = 'JS Canvas Gallery';
let meta10 = document.createElement('meta');
	meta10.name = 'theme-color';
	meta10.content = '#ffffff';
document.head.appendChild(meta1);
document.head.appendChild(meta2);
document.head.appendChild(meta3);
document.head.appendChild(meta4);
document.head.appendChild(meta5);
document.head.appendChild(meta6);
document.head.appendChild(meta7);
document.head.appendChild(meta8);
document.head.appendChild(meta9);
document.head.appendChild(meta10);